spring:
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS # ??? ? ?? ?? ?? - ?? ?? ? ANSI ??? ?? ??? (ALWAYS)
logging:
  level:
    com:
      back: debug # com.back ???? ?? ??? debug? ??
server:
  port: 8080