spring:
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS # ??? ? ?? ?? ?? - ?? ?? ? ANSI ??? ?? ??? (ALWAYS)
  jackson:
    serialization:
      fail-on-empty-beans: false # ? ?? ??? ? ?? ?? ?? (false)
logging:
  level:
    com:
      back: debug # com.back ???? ?? ??? debug? ??
server:
  port: 8080